const express = require("express");
const app = express();
const cors = require("cors");
const PORT = 8000;

app.use(cors());

const baseballStadium = {
  "arizona diamondbacks": {
    name: "Chase Field",
    location: "Phoenix, Arizona",
    capacity: 48405,
    opened: 1998,
    surface: "Artificial turf",
    distance: 407,
    roof: "Retractable",
  },
  "atlanta braves": {
    name: "Truist Park",
    location: "Cumberland, Georgia",
    capacity: 41084,
    opened: 2017,
    surface: "Grass",
    distance: 400,
    roof: "Open",
  },
  "baltimore orioles": {
    name: "Oriole Park at Camden Yards",
    location: "Baltimore, Maryland",
    capacity: 45971,
    opened: 1992,
    surface: "Grass",
    center: 410,
    roof: "Open",
  },
  "boston red sox": {
    name: "Fenway Park",
    location: "Boston, Massachusetts",
    capacity: 37755,
    opened: 1912,
    surface: "Grass",
    center: 390,
    roof: "Open",
  },
  "chicago cubs": {
    name: "Wrigley Field",
    location: "Chicago, Illinois",
    capacity: 41649,
    opened: 1914,
    surface: "Grass",
    center: 400,
    roof: "Open",
  },
  "chicago white sox": {
    name: "Guaranteed Rate Field",
    location: "Chicago, Illinois",
    capacity: 40615,
    opened: 1991,
    surface: "Grass",
    center: 400,
    roof: "Open",
  },
  "cincinnati reds": {
    name: "Great American Ball Park",
    location: "Cincinnati, Ohio",
    capacity: 42319,
    opened: 2003,
    surface: "Grass",
    center: 404,
    roof: "Open",
  },
  "cleveland guardians": {
    name: "Progressive Field",
    location: "Cleveland, Ohio",
    capacity: 34830,
    opened: 1994,
    surface: "Grass",
    center: 410,
    roof: "Open",
  },
  "colorado rockies": {
    name: "Coors Field",
    location: "Denver, Colorado",
    capacity: 50144,
    opened: 1995,
    surface: "Grass",
    center: 415,
    roof: "Open",
  },
  "detroit tigers": {
    name: "Comerica Park",
    location: "Detroit, Michigan",
    capacity: 41083,
    opened: 2000,
    surface: "Grass",
    center: 420,
    roof: "Open",
  },
  "houston astros": {
    name: "Minute Maid Park",
    location: "Houston, Texas",
    capacity: 41168,
    opened: 2000,
    surface: "Grass",
    center: 409,
    roof: "Retractable",
  },
  "kansas city royals": {
    name: "Kauffman Stadium",
    location: "Kansas City, Missouri",
    capacity: 37903,
    opened: 1973,
    surface: "Grass",
    center: 410,
    roof: "Open",
  },
  "los angeles angels": {
    name: "Angel Stadium",
    location: "Anaheim, California",
    capacity: 45517,
    opened: 1966,
    surface: "Grass",
    center: 396,
    roof: "Open",
  },
  "los angeles dodgers": {
    name: "Dodger Stadium",
    location: "Los Angeles, California",
    capacity: 56000,
    opened: 1962,
    surface: "Grass",
    center: 395,
    roof: "Open",
  },
  "miami marlins": {
    name: "LoanDepot Park",
    location: "Miami, Florida",
    capacity: 36742,
    opened: 2012,
    surface: "Artificial turf",
    center: 407,
    roof: "Retractable",
  },
  "milwaukee brewers": {
    name: "American Family Field",
    location: "Milwaukee, Wisconsin",
    capacity: 41900,
    opened: 2001,
    surface: "Grass",
    center: 400,
    roof: "Retractable",
  },
  "minnesota twins": {
    name: "Target Field",
    location: "Minneapolis, Minnesota",
    capacity: 38544,
    opened: 2010,
    surface: "Grass",
    center: 404,
    roof: "Open",
  },
  "new york mets": {
    name: "Citi Field",
    location: "Queens, New York",
    capacity: 41922,
    opened: 2009,
    surface: "Grass",
    center: 408,
    roof: "Open",
  },
  "new york yankees": {
    name: "Yankee Stadium",
    location: "Bronx, New York",
    capacity: 46537,
    opened: 2009,
    surface: "Grass",
    center: 408,
    roof: "Open",
  },
  "oakland athletics": {
    name: "RingCentral Coliseum",
    location: "Oakland, California",
    capacity: 46847,
    opened: 1966,
    surface: "Grass",
    center: 400,
    roof: "Open",
  },
  "philadelphia phillies": {
    name: "Citizens Bank Park",
    location: "Philadelphia, Pennsylvania",
    capacity: 42792,
    opened: 2004,
    surface: "Grass",
    center: 401,
    roof: "Open",
  },
  "pittsburgh pirates": {
    name: "PNC Park",
    location: "Pittsburgh, Pennsylvania",
    capacity: 38747,
    opened: 2001,
    surface: "Grass",
    center: 399,
    roof: "Open",
  },
  "san diego padres": {
    name: "Petco Park",
    location: "San Diego, California",
    capacity: 40209,
    opened: 2004,
    surface: "Grass",
    center: 396,
    roof: "Open",
  },
  "san francisco giants": {
    name: "Oracle Park",
    location: "San Francisco, California",
    capacity: 41265,
    opened: 2000,
    surface: "Grass",
    center: 391,
    roof: "Open",
  },
  "seattle mariners": {
    name: "T-Mobile Park",
    location: "Seattle, Washington",
    capacity: 47929,
    opened: 1999,
    surface: "Grass",
    center: 401,
    roof: "Retractable",
  },
  "st. louis cardinals": {
    name: "Busch Stadium",
    location: "St. Louis, Missouri",
    capacity: 45494,
    opened: 2006,
    surface: "Grass",
    center: 400,
    roof: "Open",
  },
  "tampa bay rays": {
    name: "Tropicana Field",
    location: "St. Petersburg, Florida",
    capacity: 25000,
    opened: 1990,
    surface: "Artificial turf",
    center: 404,
    roof: "Fixed",
  },
  "texas rangers": {
    name: "Globe Life Field",
    location: "Arlington, Texas",
    capacity: 40300,
    opened: 2020,
    surface: "Artificial turf",
    center: 407,
    roof: "Retractable",
  },
  "toronto blue jays": {
    name: "Rogers Centre",
    location: "Toronto, Ontario",
    capacity: 49286,
    opened: 1989,
    surface: "Artificial turf",
    center: 400,
    roof: "Retractable",
  },
  "washington nationals": {
    name: "Nationals Park",
    location: "Washington, D.C.",
    capacity: 41339,
    opened: 2008,
    surface: "Grass",
    center: 402,
    roof: "Open",
  },
  unknown: {
    name: "unknown",
    location: "unknown",
    capacity: "unknown",
    opened: "unknown",
    surface: "unknown",
    center: "unknown",
    roof: "unknown",
  },
};

app.get("/", (req, res) => {
  res.sendFile(__dirname + "/index.html");
});

app.get("/api/:teamName", (req, res) => {
  const teamName = req.params.teamName.toLocaleLowerCase();
  if (baseballStadium[teamName]) {
    res.json(baseballStadium[teamName]);
  } else {
    res.json(baseballStadium["unknown"]);
  }
});

app.listen(process.env.PORT || PORT, () => {
  console.log(`The server is running on port ${PORT}`);
});
